//THIS CAN BE USED IN DIFFERENT CONTEXTS - AS JAVASCRIPT IS A CLASSLESS LANGUAGE WE'LL USE OBJECTS INSTEAD, AND HERE WE
//USE THIS IN DIFFERENT WAYS TO INTERACT WITH THE OBJECT

console.log((this === window));